# Cloud Build configuration for Cloud Run deployment
steps:
  # Build Docker image (TypeScript compilation happens inside Dockerfile)
  # Using 'latest' tag for simplicity (always works)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/dms-api:latest'
      - '.'
  
  # Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/dms-api:latest'
  
  # Deploy to Cloud Run
  # Use 'latest' tag for deployment (always available)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'dms-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/dms-api:latest'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'NODE_ENV=production,FIREBASE_PROJECT_ID=$PROJECT_ID'

images:
  - 'gcr.io/$PROJECT_ID/dms-api:latest'

options:
  logging: CLOUD_LOGGING_ONLY
